// Données officielles des contacts et de l'annuaire de la Faculté des Sciences - Université de Yaoundé I
// Source officielle : Décanat & Secrétariat (facsciences.uy1.cm)

export interface OfficialContact {
  id: number;
  name: string;
  category: "decanat" | "departement" | "service" | "technique";
  categoryLabel: string;
  code?: string;
  emails: string[];
  role: string;
  location: string;
  priority?: boolean;
}

export const generalContactInfo = {
  phone: "(+237) 222 23 44 96",
  phoneRaw: "+237222234496",
  bp: "BP: 812 Yaoundé-Cameroun",
  site: "https://facsciences.uy1.cm",
  siteDisplay: "facsciences.uy1.cm",
  locationName: "Plateau Atemengue, Ngoa-Ekellé",
  city: "Yaoundé, Cameroun",
  institution: "Faculté des Sciences · Université de Yaoundé I",
  openingHours: {
    administration: "Lundi – Vendredi : 07h30 – 15h30",
    studentServices: "Guichets Scolarité & Diplômes : 08h30 – 14h00",
    timeZone: "Heure de Yaoundé (GMT+1)",
  },
  priorityEmails: [
    { label: "Le Doyen", email: "doyen@facsciences.uy1.cm", secondary: "Secretariat.doyen@facsciences.uy1.cm" },
    { label: "Secrétariat Général", email: "secretariat@facsciences.uy1.cm" },
    { label: "Scolarité", email: "scolarite@facsciences.uy1.cm" },
    { label: "Service Diplômes", email: "diplome@facsciences.uy1.cm" },
    { label: "Cellule Informatique", email: "ci@facsciences.uy1.cm" },
    { label: "Support & Administration", email: "admin@facsciences.uy1.cm", secondary: "support@facsciences.uy1.cm" },
  ],
};

export const officialContactsDirectory: OfficialContact[] = [
  {
    id: 1,
    name: "LE DOYEN",
    category: "decanat",
    categoryLabel: "Décanat",
    code: "DOY",
    emails: ["doyen@facsciences.uy1.cm", "Secretariat.doyen@facsciences.uy1.cm"],
    role: "Direction générale, coordination des services administratifs et académiques",
    location: "Campus Principal — Bloc Décanat, 1er Étage",
    priority: true,
  },
  {
    id: 2,
    name: "Secrétariat de la Faculté des Sciences",
    category: "decanat",
    categoryLabel: "Décanat & Secrétariat",
    code: "SEC",
    emails: ["secretariat@facsciences.uy1.cm"],
    role: "Accueil institutionnel, courrier officiel, relations publiques et partenariats",
    location: "Campus Principal — Bâtiment Administratif",
    priority: true,
  },
  {
    id: 3,
    name: "Département de Mathématiques – MA",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "MA",
    emails: ["cdma@facsciences.uy1.cm", "cdma.secretariat@facsciences.uy1.cm"],
    role: "Formation fondamentale et appliquée en Mathématiques, Algèbre, Analyse et Modélisation",
    location: "Campus Principal — Bâtiment des Mathématiques",
  },
  {
    id: 4,
    name: "Département d’Informatique – IN",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "IN",
    emails: ["cdin@facsciences.uy1.cm", "cdin.secretariat@facsciences.uy1.cm"],
    role: "Génie logiciel, réseaux, intelligence artificielle, systèmes distribués et data science",
    location: "Campus Principal — Centre de Calcul & Département Informatique",
  },
  {
    id: 5,
    name: "Département de Physique – PH",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "PH",
    emails: ["cdph@facsciences.uy1.cm", "cdph.secretariat@facsciences.uy1.cm"],
    role: "Mécanique, électronique, optique, énergies renouvelables et physique des matériaux",
    location: "Campus Principal — Aile Physique & Laboratoires",
  },
  {
    id: 6,
    name: "Département de Biochimie – BC",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "BC",
    emails: ["cdbc@facsciences.uy1.cm", "cdbc.secretariat@facsciences.uy1.cm"],
    role: "Biochimie clinique, enzymologie, biologie moléculaire et toxicologie",
    location: "Campus Principal — Bloc Sciences de la Vie",
  },
  {
    id: 7,
    name: "Département de Biologie et Physiologie Animal – BPA",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "BPA",
    emails: ["cdbpa@facsciences.uy1.cm", "cdbpa.secretariat@facsciences.uy1.cm"],
    role: "Zoologie, physiologie comparée, parasitologie, entomologie et hydrobiologie",
    location: "Campus Principal — Laboratoires de Biologie Animale",
  },
  {
    id: 8,
    name: "Département de Biologie et Physiologie Végétales – BPV",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "BPV",
    emails: ["cdbpv@facsciences.uy1.cm", "cdbpv.secretariat@facsciences.uy1.cm"],
    role: "Botanique systématique, biotechnologie végétale, phytopathologie et écologie",
    location: "Campus Principal — Laboratoires de Biologie Végétale & Herbier",
  },
  {
    id: 9,
    name: "Département de Microbiologie – MIB",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "MIB",
    emails: ["cdmib@facsciences.uy1.cm", "cdmib.secretariat@facsciences.uy1.cm"],
    role: "Bactériologie, virologie, mycologie médicale, immunologie et biotechnologie industrielle",
    location: "Campus Principal — Laboratoires de Microbiologie",
  },
  {
    id: 10,
    name: "Département de Chimie Inorganique – CI",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "CI",
    emails: ["cdci@facsciences.uy1.cm", "cdci.secretariat@facsciences.uy1.cm"],
    role: "Chimie minérale, chimie des matériaux, catalyse et chimie environnementale",
    location: "Campus Principal — Bâtiment de Chimie",
  },
  {
    id: 11,
    name: "Département de Sciences de la Terre – ST",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "ST",
    emails: ["cdst@facsciences.uy1.cm", "cdst.secretariat@facsciences.uy1.cm"],
    role: "Géologie, géochimie, géophysique, métallogénie et cartographie des formations rocheuses",
    location: "Campus Principal — Bâtiment Sciences de la Terre",
  },
  {
    id: 12,
    name: "Département de Chimie Organique – CO",
    category: "departement",
    categoryLabel: "Département Académique",
    code: "CO",
    emails: ["cdco@facsciences.uy1.cm", "cdco.secretariat@facsciences.uy1.cm"],
    role: "Synthèse organique, phytochimie, valorisation des substances naturelles et pharmacochimie",
    location: "Campus Principal — Bâtiment de Chimie",
  },
  {
    id: 13,
    name: "Chef de Service de Diplômes",
    category: "service",
    categoryLabel: "Service Central",
    code: "DIP",
    emails: ["diplome@facsciences.uy1.cm"],
    role: "Édition, authentification, vérification et délivrance des attestations et diplômes officiels",
    location: "Campus Principal — DAARS / Guichet Diplômes",
    priority: true,
  },
  {
    id: 14,
    name: "Chef de Service de Langue",
    category: "service",
    categoryLabel: "Service Central",
    code: "LAN",
    emails: ["langue@facsciences.uy1.cm"],
    role: "Coordination des formations bilingues (Français / Anglais) et certifications linguistiques",
    location: "Campus Principal — Centre de Ressources Linguistiques",
  },
  {
    id: 15,
    name: "Chef de Service de Scolarité",
    category: "service",
    categoryLabel: "Service Central",
    code: "SCO",
    emails: ["scolarite@facsciences.uy1.cm"],
    role: "Inscriptions académiques, dossiers étudiants, transferts et registres d'examens",
    location: "Campus Principal — Hall Central de la Scolarité",
    priority: true,
  },
  {
    id: 16,
    name: "Chef de Service du Personnel",
    category: "service",
    categoryLabel: "Service Central",
    code: "PERS",
    emails: ["personnel@facsciences.uy1.cm"],
    role: "Gestion des carrières des enseignants-chercheurs et du personnel administratif",
    location: "Campus Principal — Division Administrative et Financière (DAF)",
  },
  {
    id: 17,
    name: "Chef de Service de Maintenance et du Matériel",
    category: "service",
    categoryLabel: "Service Central",
    code: "MAINT",
    emails: ["maintenance@facsciences.uy1.cm"],
    role: "Maintenance des infrastructures, équipements des laboratoires et intendance des campus",
    location: "Campus Principal & Extension — Services Techniques",
  },
  {
    id: 18,
    name: "Chef de Service de Financier",
    category: "service",
    categoryLabel: "Service Central",
    code: "FIN",
    emails: ["finance@facsciences.uy1.cm"],
    role: "Comptabilité, régie des recettes, gestion des bourses et suivi budgétaire",
    location: "Campus Principal — Division Administrative et Financière (DAF)",
  },
  {
    id: 19,
    name: "Cellule Informatique",
    category: "technique",
    categoryLabel: "Pôle Technique & IT",
    code: "CI",
    emails: ["ci@facsciences.uy1.cm"],
    role: "Infrastructures réseau, portail universitaire, hébergement des plateformes pédagogiques",
    location: "Campus Principal — Centre de Télé-Enseignement / Cellule IT",
    priority: true,
  },
  {
    id: 20,
    name: "Support Technique",
    category: "technique",
    categoryLabel: "Pôle Technique & IT",
    code: "SUP",
    emails: ["support@facsciences.uy1.cm", "admin@facsciences.uy1.cm"],
    role: "Assistance aux utilisateurs, réinitialisation des accès académiques et requêtes techniques",
    location: "En ligne & Guichet Support — Campus Principal",
    priority: true,
  },
];
