// Répertoire officiel des enseignants permanents de la Faculté des Sciences UY1
// Année académique 2023/2024 (Actualisation : 16 décembre 2024)

export type Teacher = {
  num: number;
  name: string;
  rank: string;
  observation: string;
};

export type DepartmentStaff = {
  id: string;
  code: string;
  name: string;
  count: number;
  teachers: Teacher[];
};

export type StaffStatRow = {
  code: string;
  name: string;
  prof: string;
  mc: string;
  cc: string;
  asst: string;
  total: string;
};

export const protocolDocument = {
  title: "Liste protocolaire au 20 Mars 2024 de la Faculté des Sciences de l'Université de Yaoundé I",
  url: "https://facsciences.uy1.cm/wp-content/uploads/2024/03/liste-protocolaire-au-20-Mars-2024-de-la-Faculte-des-Sciences-de-lUniversite-de-Yaounde-I.pdf",
  date: "16 décembre 2024",
  academicYear: "2023/2024",
};

export const staffSummary = {
  total: 318,
  totalWomen: 75,
  prof: { count: 61, women: 4 },
  mc: { count: 97, women: 25 },
  cc: { count: 141, women: 39 },
  asst: { count: 19, women: 6 },
};

export const staffStatsTable: StaffStatRow[] = [
  { code: "BCH", name: "Biochimie", prof: "5 (1)", mc: "12 (6)", cc: "19 (11)", asst: "1 (1)", total: "37 (19)" },
  { code: "BPA", name: "Biologie et Physiologie Animales", prof: "12 (1)", mc: "10 (5)", cc: "20 (7)", asst: "2 (0)", total: "44 (13)" },
  { code: "BPV", name: "Biologie et Physiologie Végétales", prof: "5 (0)", mc: "10 (2)", cc: "9 (4)", asst: "2 (2)", total: "26 (9)" },
  { code: "CI", name: "Chimie Inorganique", prof: "9 (1)", mc: "9 (2)", cc: "14 (3)", asst: "0 (0)", total: "32 (6)" },
  { code: "CO", name: "Chimie Organique", prof: "7 (0)", mc: "14 (4)", cc: "10 (4)", asst: "1 (0)", total: "32 (8)" },
  { code: "IN", name: "Informatique", prof: "2 (0)", mc: "1 (0)", cc: "13 (0)", asst: "10 (3)", total: "26 (3)" },
  { code: "MAT", name: "Mathématiques", prof: "2 (0)", mc: "4 (1)", cc: "19 (1)", asst: "2 (0)", total: "27 (2)" },
  { code: "MIB", name: "Microbiologie", prof: "2 (0)", mc: "5 (2)", cc: "5 (1)", asst: "0 (0)", total: "12 (3)" },
  { code: "PHY", name: "Physique", prof: "10 (0)", mc: "17 (2)", cc: "11 (3)", asst: "1 (0)", total: "39 (5)" },
  { code: "ST", name: "Sciences de la Terre", prof: "7 (1)", mc: "15 (1)", cc: "21 (5)", asst: "1 (0)", total: "43 (7)" },
];

export const administrationStaff = {
  decanat: [
    { title: "Doyen", name: "OWONO OWONO Luc Calvin", rank: "Professeur", code: "DOYEN" },
    { title: "Vice-Doyen / DPSAA", name: "NDJIGUI Paul-Désiré", rank: "Professeur", code: "DPSAA", roleDesc: "Programmation et Suivi des Activités Académiques" },
    { title: "Vice-Doyen / DSSE", name: "NYEGUE Maximilienne Ascension", rank: "Professeur", code: "DSSE", roleDesc: "Scolarité, Statistiques et Suivi des Étudiants" },
    { title: "Vice-Doyen / DRC", name: "NOUNDJEU Pierre", rank: "Maître de Conférences", code: "DRC", roleDesc: "Recherche et Coopération" },
  ],
  daf: [
    { title: "Chef de Division", name: "NDOYE FOE Marie C. F.", rank: "Maître de Conférences", role: "Division Administrative et Financière" },
    { title: "Chef de Service", name: "NTONGA Emmanuel Didier", rank: "PLEG", role: "Administration Générale et Personnel (SAGP)" },
    { title: "Chef de Service", name: "EPOH NDOMA Wilfried Ghislain", rank: "CPJA", role: "Service Financier" },
    { title: "Chef de Service", name: "BIKOMO Marthe Désirée épse OYONO", rank: "CCA", role: "Matériel et Maintenance" },
    { title: "Chef de Service Adjoint", name: "ENGUENE EVA Ynes épse MBOG", rank: "IEMP", role: "Service Adjoint du SAGP" },
    { title: "Chef de Service Adjoint", name: "ANNY MBOGNE Jacqueline Gwladys", rank: "CPOSUP", role: "Service Adjoint Financier" },
  ],
  daars: [
    { title: "Chef de Division", name: "AJEAGAH Gideon AGHAINDUM", rank: "Professeur", role: "Division des Affaires Académiques, Scolarité et Recherche (DAARS)" },
    { title: "Chef de Service", name: "TCHIKOUA Roger", rank: "Maître de Conférences", role: "Scolarité et Statistiques" },
    { title: "Chef de Service", name: "Isabelle Sandrine BOUELET NTSAMA", rank: "Chargée de Cours", role: "Diplômes, Programmes d’Enseignement et de Recherche" },
    { title: "Chef de Service Adjoint", name: "ONANA Jacques Bertrand", rank: "Chargé de Cours Assistant", role: "Service Adjoint Scolarité et Statistiques" },
    { title: "Chef de Service Adjoint", name: "YADANG Germaine épse SOULEY", rank: "Chargée de Cours", role: "Service Adjoint Diplômes et Recherche" },
  ],
  departmentHeads: [
    { dept: "Biochimie", head: "MOUNDIPA FEWO Paul", rank: "Professeur" },
    { dept: "Biologie et Physiologie Animales", head: "BILONG BILONG Charles Félix (décédé)", rank: "Professeur" },
    { dept: "Biologie et Physiologie Végétales", head: "AMBANG Zachée", rank: "Professeur" },
    { dept: "Chimie Inorganique", head: "NDI Julius NSAME", rank: "Maître de Conférences" },
    { dept: "Chimie Organique", head: "PEGNYEMB Emmanuel Dieudonné", rank: "Professeur" },
    { dept: "Énergies Renouvelables", head: "BODO Bertrand", rank: "Maître de Conférences" },
    { dept: "Informatique", head: "AMINOU HALIDOU", rank: "Chargé de Cours" },
    { dept: "Mathématiques", head: "AYISSI Raoul Domingo", rank: "Professeur" },
    { dept: "Microbiologie", head: "ESSIA NGANG Jean Justin", rank: "Professeur" },
    { dept: "Physique", head: "NDJAKA Jean Marie Bienvenu", rank: "Professeur" },
    { dept: "Sciences de la Terre et de l'Univers", head: "NDJIGUI Paul Désiré", rank: "Professeur" },
    { dept: "Service des Langues", head: "FONKOUA Paul", rank: "Chargé de Cours" },
  ],
};

export const departmentsTeachingStaff: DepartmentStaff[] = [
  {
    id: "biochimie",
    code: "BCH",
    name: "Département de Biochimie",
    count: 37,
    teachers: [
      { num: 1, name: "FEKAM BOYOM Fabrice", rank: "Professeur", observation: "En poste" },
      { num: 2, name: "MBACHAM FON Wilfried", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "MOUNDIPA FEWOU Paul", rank: "Professeur", observation: "Chef de Département" },
      { num: 4, name: "NINTCHOM PENLAP V. épse BENG", rank: "Professeur", observation: "En poste" },
      { num: 5, name: "OBEN Julius ENYONG", rank: "Professeur", observation: "En poste" },
      { num: 6, name: "ACHU Merci BIH", rank: "Maître de Conférences", observation: "En poste" },
      { num: 7, name: "ATOGHO Barbara Mma", rank: "Maître de Conférences", observation: "En poste" },
      { num: 8, name: "BELINGA née NDOYE FOE M. C. F.", rank: "Maître de Conférences", observation: "Chef DAF / FS" },
      { num: 9, name: "BIGOGA DIAGA Jude", rank: "Maître de Conférences", observation: "En poste" },
      { num: 10, name: "BOUDJEKO Thaddée", rank: "Maître de Conférences", observation: "En poste" },
      { num: 11, name: "EFFA NNOMO Pierre", rank: "Maître de Conférences", observation: "En poste" },
      { num: 12, name: "FOKOU Elie", rank: "Maître de Conférences", observation: "En poste" },
      { num: 13, name: "KANSCI Germain", rank: "Maître de Conférences", observation: "En poste" },
      { num: 14, name: "NANA Louise épouse WAKAM", rank: "Maître de Conférences", observation: "En poste" },
      { num: 15, name: "NGONDI Judith Laure", rank: "Maître de Conférences", observation: "En poste" },
      { num: 16, name: "NGUEFACK Julienne", rank: "Maître de Conférences", observation: "En poste" },
      { num: 17, name: "NJAYOU Frédéric Nico", rank: "Maître de Conférences", observation: "En poste" },
      { num: 18, name: "AKINDEH MBUH NJI", rank: "Chargée de Cours", observation: "En poste" },
      { num: 19, name: "AZANTSA KINGUE GABIN BORIS", rank: "Chargé de Cours", observation: "En poste" },
      { num: 20, name: "BEBOY EDZENGUELE Sara Nathalie", rank: "Chargée de Cours", observation: "En poste" },
      { num: 21, name: "DAKOLE DABOY Charles", rank: "Chargé de Cours", observation: "En poste" },
      { num: 22, name: "DJOKAM TAMO Rosine", rank: "Chargée de Cours", observation: "En poste" },
      { num: 23, name: "DJUIDJE NGOUNOUE Marcelline", rank: "Chargée de Cours", observation: "En poste" },
      { num: 24, name: "DJUIKWO NKONGA Ruth Viviane", rank: "Chargée de Cours", observation: "En poste" },
      { num: 25, name: "DONGMO LEKAGNE Joseph Blaise", rank: "Chargé de Cours", observation: "En poste" },
      { num: 26, name: "EWANE Cécile Anne", rank: "Chargée de Cours", observation: "En poste" },
      { num: 27, name: "FONKOUA Martin", rank: "Chargé de Cours", observation: "En poste" },
      { num: 28, name: "BEBEE Fadimatou", rank: "Chargée de Cours", observation: "En poste" },
      { num: 29, name: "KOTUE KAPTUE Charles", rank: "Chargé de Cours", observation: "En poste" },
      { num: 30, name: "LUNGA Paul KEILAH", rank: "Chargé de Cours", observation: "En poste" },
      { num: 31, name: "MANANGA Marlyse Joséphine", rank: "Chargée de Cours", observation: "En poste" },
      { num: 32, name: "MBONG ANGIE M. Mary Anne", rank: "Chargée de Cours", observation: "En poste" },
      { num: 33, name: "MOFOR née TEUGWA Clotilde", rank: "Chargée de Cours", observation: "Inspecteur de Service MINESUP" },
      { num: 34, name: "PACHANGOU NSANGOU Sylvain", rank: "Chargé de Cours", observation: "En poste" },
      { num: 35, name: "Palmer MASUMBE NETONGO", rank: "Chargé de Cours", observation: "En poste" },
      { num: 36, name: "TCHANA KOUATCHOUA Angèle", rank: "Chargée de Cours", observation: "En poste" },
      { num: 37, name: "MBOUCHE FANMOE Marceline Joëlle", rank: "Assistante", observation: "En poste" },
    ],
  },
  {
    id: "biologie-physiologie-animales",
    code: "BPA",
    name: "Département de Biologie et Physiologie Animales",
    count: 44,
    teachers: [
      { num: 1, name: "BILONG BILONG Charles-Félix", rank: "Professeur", observation: "Chef de Département (décédé)" },
      { num: 2, name: "DIMO Théophile", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "DJIETO LORDON Champlain", rank: "Professeur", observation: "En poste" },
      { num: 4, name: "ESSOMBA née NTSAMA MBALA", rank: "Professeur", observation: "VDoyen/FMSB/UYI" },
      { num: 5, name: "FOMENA Abraham", rank: "Professeur", observation: "En poste" },
      { num: 6, name: "KAMGANG René", rank: "Professeur", observation: "C.S. MINRESI" },
      { num: 7, name: "KAMTCHOUING Pierre", rank: "Professeur", observation: "En poste" },
      { num: 8, name: "NJAMEN Dieudonné", rank: "Professeur", observation: "En poste" },
      { num: 9, name: "NJIOKOU Flobert", rank: "Professeur", observation: "En poste" },
      { num: 10, name: "NOLA Moïse", rank: "Professeur", observation: "En poste" },
      { num: 11, name: "TAN Paul VERNYUY", rank: "Professeur", observation: "En poste" },
      { num: 12, name: "TCHUEM TCHUENTE Louis Albert", rank: "Professeur", observation: "Inspecteur de service Coord.Progr./MINSANTE" },
      { num: 13, name: "AJEAGAH Gideon AGHAINDUM", rank: "Maître de Conférences", observation: "Chef DAARS / Vice-Doyen" },
      { num: 14, name: "DZEUFIET DJOMENI Paul Désiré", rank: "Maître de Conférences", observation: "En poste" },
      { num: 15, name: "FOTO MENBOHAN Samuel", rank: "Maître de Conférences", observation: "En poste" },
      { num: 16, name: "KEKEUNOU Sévilor", rank: "Maître de Conférences", observation: "En poste" },
      { num: 17, name: "MEGNEKOU Rosette", rank: "Maître de Conférences", observation: "En poste" },
      { num: 18, name: "MONY Ruth épse NTONE", rank: "Maître de Conférences", observation: "En poste" },
      { num: 19, name: "NGUEGUIM TSOFACK Florence", rank: "Maître de Conférences", observation: "En poste" },
      { num: 20, name: "JATSA BOUKENG Hermine épse MEGAPTCHE", rank: "Maître de Conférences", observation: "En poste" },
      { num: 21, name: "TOMBI Jeannette", rank: "Maître de Conférences", observation: "En poste" },
      { num: 22, name: "ZEBAZE TOGOUET Serge Hubert", rank: "Maître de Conférences", observation: "En poste" },
      { num: 23, name: "ALENE Désirée Chantal", rank: "Chargée de Cours", observation: "En poste" },
      { num: 24, name: "ATSAMO Albert Donatien", rank: "Chargé de Cours", observation: "En poste" },
      { num: 25, name: "BELLET EDIMO Oscar Roger", rank: "Chargé de Cours", observation: "En poste" },
      { num: 26, name: "BILANDA Danielle Claude", rank: "Chargée de Cours", observation: "En poste" },
      { num: 27, name: "DJIOGUE Séfirin", rank: "Chargé de Cours", observation: "En poste" },
      { num: 28, name: "DONFACK Mireille", rank: "Chargée de Cours", observation: "En poste" },
      { num: 29, name: "GOUNOUE KAMKUMO Raceline", rank: "Chargée de Cours", observation: "En poste" },
      { num: 30, name: "KANDEDA KAVAYE Antoine", rank: "Chargé de Cours", observation: "En poste" },
      { num: 31, name: "LEKEUFACK FOLEFACK Guy B.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 32, name: "MAHOB Raymond Joseph", rank: "Chargé de Cours", observation: "En poste" },
      { num: 33, name: "MBENOUN MASSE Paul Serge", rank: "Chargé de Cours", observation: "En poste" },
      { num: 34, name: "MOUNGANG Luciane Marlyse", rank: "Chargée de Cours", observation: "En poste" },
      { num: 35, name: "MVEYO NDANKEU Yves Patrick", rank: "Chargé de Cours", observation: "En poste" },
      { num: 36, name: "NGOUATEU KENFACK Omer Bébé", rank: "Chargé de Cours", observation: "En poste" },
      { num: 37, name: "NGUEMBOK", rank: "Chargé de Cours", observation: "En poste" },
      { num: 38, name: "NJUA Clarisse Yafi", rank: "Chargée de Cours", observation: "Chef Div. UBA" },
      { num: 39, name: "NOAH EWOTI Olive Vivien", rank: "Chargée de Cours", observation: "En poste" },
      { num: 40, name: "TADU Zephyrin", rank: "Chargé de Cours", observation: "En poste" },
      { num: 41, name: "YEDE", rank: "Chargé de Cours", observation: "En poste" },
      { num: 42, name: "ETEME ENAMA Serge", rank: "Assistant", observation: "En poste" },
      { num: 43, name: "KOGA MANG DOBARA", rank: "Assistant", observation: "En poste" },
    ],
  },
  {
    id: "biologie-physiologie-vegetales",
    code: "BPV",
    name: "Département de Biologie et Physiologie Végétales",
    count: 27,
    teachers: [
      { num: 1, name: "AMBANG Zachée", rank: "Professeur", observation: "Chef Division/UYII" },
      { num: 2, name: "BELL Joseph Martin", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "MOSSEBO Dominique Claude", rank: "Professeur", observation: "En poste" },
      { num: 4, name: "YOUMBI Emmanuel", rank: "Professeur", observation: "Chef de Département" },
      { num: 5, name: "ZAPFACK Louis", rank: "Professeur", observation: "En poste" },
      { num: 6, name: "ANGONI Hyacinthe", rank: "Maître de Conférences", observation: "En poste" },
      { num: 7, name: "BIYE Elvire Hortense", rank: "Maître de Conférences", observation: "En poste" },
      { num: 8, name: "DJOCGOUE Pierre François", rank: "Maître de Conférences", observation: "En poste" },
      { num: 9, name: "KENGNE NOUMSI Ives Magloire", rank: "Maître de Conférences", observation: "En poste" },
      { num: 10, name: "MALA Armand William", rank: "Maître de Conférences", observation: "En poste" },
      { num: 11, name: "MBARGA BINDZI Marie Alain", rank: "Maître de Conférences", observation: "CT/UDs" },
      { num: 12, name: "MBOLO Marie", rank: "Maître de Conférences", observation: "En poste" },
      { num: 13, name: "NDONGO BEKOLO", rank: "Maître de Conférences", observation: "CE / MINRESI" },
      { num: 14, name: "NGONKEU MAGAPTCHE Eddy L.", rank: "Maître de Conférences", observation: "En poste" },
      { num: 15, name: "TSOATA Esaïe", rank: "Maître de Conférences", observation: "En poste" },
      { num: 16, name: "GOMANDJE Christelle", rank: "Chargée de Cours", observation: "En poste" },
      { num: 17, name: "MAFFO MAFFO Nicole Liliane", rank: "Chargée de Cours", observation: "En poste" },
      { num: 18, name: "MAHBOU SOMO TOUKAM Gabriel", rank: "Chargé de Cours", observation: "En poste" },
      { num: 19, name: "NGALLE Hermine BILLE", rank: "Chargée de Cours", observation: "En poste" },
      { num: 20, name: "NGOUO Lucas Vincent", rank: "Chargé de Cours", observation: "En poste" },
      { num: 21, name: "NOUKEU KOUAKAM Armelle", rank: "Chargée de Cours", observation: "En poste" },
      { num: 22, name: "ONANA Jean Michel", rank: "Chargé de Cours", observation: "En poste" },
      { num: 23, name: "NSOM ZAMO Annie Claude épse PIAL", rank: "Chargée de Cours", observation: "Expert national/UNESCO" },
      { num: 24, name: "TONFACK Libert Brice", rank: "Chargé de Cours", observation: "En poste" },
      { num: 25, name: "DJEUANI Astride Carole", rank: "Assistante", observation: "En poste" },
      { num: 26, name: "NNANGA MEBENGA Ruth Laure", rank: "Assistante", observation: "En poste" },
    ],
  },
  {
    id: "chimie-inorganique",
    code: "CI",
    name: "Département de Chimie Inorganique",
    count: 32,
    teachers: [
      { num: 1, name: "AGWARA ONDOH Moïse", rank: "Professeur", observation: "Vice Recteur Univ. Bamenda" },
      { num: 2, name: "ELIMBI Antoine", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "Florence UFI CHINJE épouse MELO", rank: "Professeur", observation: "Recteur Univ. Ngaoundéré" },
      { num: 4, name: "GHOGOMU Paul MINGO", rank: "Professeur", observation: "Ministre Chargé de Mission Présidence de la République" },
      { num: 5, name: "NANSEU Njiki Charles Péguy", rank: "Professeur", observation: "En poste" },
      { num: 6, name: "NDIFON Peter TEKE", rank: "Professeur", observation: "CT MINRESI / Chef de Département" },
      { num: 7, name: "NDIKONTAR Maurice KOR", rank: "Professeur", observation: "Vice-Doyen Univ. Bamenda" },
      { num: 8, name: "NENWA Justin", rank: "Professeur", observation: "En poste" },
      { num: 9, name: "NGAMENI Emmanuel", rank: "Professeur", observation: "Doyen FS UDs" },
      { num: 10, name: "BABALE née DJAM DOUDOU", rank: "Maître de Conférences", observation: "Chargée Mission P.R." },
      { num: 11, name: "DJOUFAC WOUMFO Emmanuel", rank: "Maître de Conférences", observation: "En poste" },
      { num: 12, name: "KAMGANG YOUBI Georges", rank: "Maître de Conférences", observation: "En poste" },
      { num: 13, name: "KEMMEGNE MBOUGUEM Jean C.", rank: "Maître de Conférences", observation: "En poste" },
      { num: 14, name: "KONG SAKEO", rank: "Maître de Conférences", observation: "En poste" },
      { num: 15, name: "NGOMO Horace MANGA", rank: "Maître de Conférences", observation: "Vice Chancelor / UB" },
      { num: 16, name: "NJIOMOU C. épse DJANGANG", rank: "Maître de Conférences", observation: "En poste" },
      { num: 17, name: "NJOYA Dayirou", rank: "Maître de Conférences", observation: "En poste" },
      { num: 18, name: "YOUNANG Elie", rank: "Maître de Conférences", observation: "En poste" },
      { num: 19, name: "ACAYANKA Elie", rank: "Chargé de Cours", observation: "En poste" },
      { num: 20, name: "BELIBI BELIBI Placide Désiré", rank: "Chargé de Cours", observation: "CS / ENS Bertoua" },
      { num: 21, name: "CHEUMANI YONA Arnaud M.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 22, name: "EMADACK Alphonse", rank: "Chargé de Cours", observation: "En poste" },
      { num: 23, name: "KENNE DEDZO Gustave", rank: "Chargé de Cours", observation: "En poste" },
      { num: 24, name: "KOUOTOU Daouda", rank: "Chargé de Cours", observation: "En poste" },
      { num: 25, name: "MAKON Thomas Beauregard", rank: "Chargé de Cours", observation: "En poste" },
      { num: 26, name: "MBEY Jean Aimé", rank: "Chargé de Cours", observation: "En poste" },
      { num: 27, name: "NCHIMI NONO Katia", rank: "Chargée de Cours", observation: "En poste" },
      { num: 28, name: "NDI NSAMI Julius", rank: "Chargé de Cours", observation: "En poste" },
      { num: 29, name: "NEBA née NDOSIRI Bridget NDOYE", rank: "Chargée de Cours", observation: "Inspecteur de Service MINFEM" },
      { num: 30, name: "NYAMEN Linda Dyorisse", rank: "Chargée de Cours", observation: "En poste" },
      { num: 31, name: "PABOUDAM GBAMBIE A.", rank: "Chargée de Cours", observation: "En poste" },
      { num: 32, name: "TCHAKOUTE KOUAMO Hervé", rank: "Chargé de Cours", observation: "En poste" },
    ],
  },
  {
    id: "chimie-organique",
    code: "CO",
    name: "Département de Chimie Organique",
    count: 32,
    teachers: [
      { num: 1, name: "DONGO Etienne", rank: "Professeur", observation: "Vice-Doyen / PSAA" },
      { num: 2, name: "GHOGOMU TIH Robert Ralph", rank: "Professeur", observation: "Dir. IBAF / UDS" },
      { num: 3, name: "NGOUELA Silvère Augustin", rank: "Professeur", observation: "En poste" },
      { num: 4, name: "NKENGFACK Augustin Ephreïm", rank: "Professeur", observation: "Chef de Département" },
      { num: 5, name: "NYASSE Barthélemy", rank: "Professeur", observation: "Directeur / UN" },
      { num: 6, name: "PEGNYEMB Dieudonné Emmanuel", rank: "Professeur", observation: "Directeur / MINESUP" },
      { num: 7, name: "WANDJI Jean", rank: "Professeur", observation: "En poste" },
      { num: 8, name: "Alex de Théodore ATCHADE", rank: "Maître de Conférences", observation: "DEPE / Rectorat / UYI" },
      { num: 9, name: "EYONG Kenneth OBEN", rank: "Maître de Conférences", observation: "Chef Service DPER" },
      { num: 10, name: "FOLEFOC Gabriel NGOSONG", rank: "Maître de Conférences", observation: "En poste" },
      { num: 11, name: "KEUMEDJIO Félix", rank: "Maître de Conférences", observation: "En poste" },
      { num: 12, name: "KEUMOGNE Marguerite", rank: "Maître de Conférences", observation: "En poste" },
      { num: 13, name: "KOUAM Jacques", rank: "Maître de Conférences", observation: "En poste" },
      { num: 14, name: "MBAZOA née DJAMA Céline", rank: "Maître de Conférences", observation: "En poste" },
      { num: 15, name: "MKOUNGA Pierre", rank: "Maître de Conférences", observation: "En poste" },
      { num: 16, name: "NGO MBING Joséphine", rank: "Maître de Conférences", observation: "Sous-Directeur MINRESI" },
      { num: 17, name: "NOUNGOUE TCHAMO Diderot", rank: "Maître de Conférences", observation: "En poste" },
      { num: 18, name: "TABOPDA KUATE Turibio", rank: "Maître de Conférences", observation: "En poste" },
      { num: 19, name: "TCHOUANKEU Jean-Claude", rank: "Maître de Conférences", observation: "Doyen / FS / UYI" },
      { num: 20, name: "TIH née NGO BILONG E. Anastasie", rank: "Maître de Conférences", observation: "En poste" },
      { num: 21, name: "YANKEP Emmanuel", rank: "Maître de Conférences", observation: "En poste" },
      { num: 22, name: "AMBASSA Pantaléon", rank: "Chargé de Cours", observation: "En poste" },
      { num: 23, name: "FOTSO WABO Ghislain", rank: "Chargé de Cours", observation: "En poste" },
      { num: 24, name: "KAMTO Eutrophe Le Doux", rank: "Chargé de Cours", observation: "En poste" },
      { num: 25, name: "MVOT AKAK Carine", rank: "Chargée de Cours", observation: "En poste" },
      { num: 26, name: "NGOMO Orléans", rank: "Chargée de Cours", observation: "En poste" },
      { num: 27, name: "NGONO BIKOBO Dominique Serge", rank: "Chargé de Cours", observation: "En poste" },
      { num: 28, name: "NOTE LOUGBOT Olivier Placide", rank: "Chargé de Cours", observation: "Chef Service / MINESUP" },
      { num: 29, name: "OUAHOUO WACHE Blandine M.", rank: "Chargée de Cours", observation: "En poste" },
      { num: 30, name: "TAGATSING FOTSING Maurice", rank: "Chargé de Cours", observation: "En poste" },
      { num: 31, name: "ZONDENDEGOUMBA Ernestine", rank: "Chargée de Cours", observation: "En poste" },
      { num: 32, name: "NGNINTEDO Dominique", rank: "Assistant", observation: "En poste" },
    ],
  },
  {
    id: "informatique",
    code: "IN",
    name: "Département d’Informatique",
    count: 25,
    teachers: [
      { num: 1, name: "ATSA ETOUNDI Roger", rank: "Professeur", observation: "Chef Div. MINESUP" },
      { num: 2, name: "FOUDA NDJODO Marcel Laurent", rank: "Professeur", observation: "Chef Dpt ENS / Chef IGA MINESUP" },
      { num: 3, name: "NDOUNDAM Réné", rank: "Maître de Conférences", observation: "En poste" },
      { num: 4, name: "AMINOU Halidou", rank: "Chargé de Cours", observation: "Chef de Département" },
      { num: 5, name: "DJAM Xaviera YOUHEP KIMBI", rank: "Chargée de Cours", observation: "En poste" },
      { num: 6, name: "KOUOKAM KOUOKAM E. A.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 7, name: "MELATAGIA YONTA Paulin", rank: "Chargé de Cours", observation: "En poste" },
      { num: 8, name: "MOTO MPONG Serge Alain", rank: "Chargé de Cours", observation: "En poste" },
      { num: 9, name: "TAPAMO Hyppolite", rank: "Chargé de Cours", observation: "En poste" },
      { num: 10, name: "ABESSOLO ALO’O Gislain", rank: "Chargé de Cours", observation: "En poste" },
      { num: 11, name: "KAMGUEU Patrick Olivier", rank: "Chargé de Cours", observation: "En poste" },
      { num: 12, name: "MONTHE DJIADEU Valery M.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 13, name: "OLLE OLLE Daniel Claude Delort", rank: "Chargé de Cours", observation: "C/D Enset. Ebolowa" },
      { num: 14, name: "TINDO Gilbert", rank: "Chargé de Cours", observation: "En poste" },
      { num: 15, name: "TSOPZE Norbert", rank: "Chargé de Cours", observation: "En poste" },
      { num: 16, name: "WAKU KOUAMOU Jules", rank: "Chargé de Cours", observation: "En poste" },
      { num: 17, name: "BAYEM Jacques Narcisse", rank: "Assistant", observation: "En poste" },
      { num: 18, name: "DOMGA KOMGUEM Rodrigue", rank: "Assistant", observation: "En poste" },
      { num: 19, name: "EBELE Serge", rank: "Assistant", observation: "En poste" },
      { num: 20, name: "HAMZA Adamou", rank: "Assistant", observation: "En poste" },
      { num: 21, name: "JIOMEKONG AZANZI Fidel", rank: "Assistant", observation: "En poste" },
      { num: 22, name: "KAMDEM KENGNE Christiane", rank: "Assistante", observation: "En poste" },
      { num: 23, name: "MAKEMBE S. Oswald", rank: "Assistant", observation: "En poste" },
      { num: 24, name: "MEYEMDOU Nadège Sylvianne", rank: "Assistante", observation: "En poste" },
      { num: 25, name: "NKONDOCK MI BAHANACK N.", rank: "Assistant", observation: "En poste" },
    ],
  },
  {
    id: "mathematiques",
    code: "MA",
    name: "Département de Mathématiques",
    count: 28,
    teachers: [
      { num: 1, name: "BITJONG NDOMBOL", rank: "Professeur", observation: "En poste" },
      { num: 2, name: "DOSSA COSSY Marcel", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "AYISSI Raoul Domingo", rank: "Maître de Conférences", observation: "Chef de Département" },
      { num: 4, name: "EMVUDU WONO Yves S.", rank: "Maître de Conférences", observation: "CD Info / Chef division MINESUP" },
      { num: 5, name: "NKUIMI JUGNIA Célestin", rank: "Maître de Conférences", observation: "En poste" },
      { num: 6, name: "NOUNDJEU Pierre", rank: "Maître de Conférences", observation: "Vice-Doyen / DRC" },
      { num: 7, name: "TCHAPNDA NJABO Sophonie B.", rank: "Maître de Conférences", observation: "Directeur / AIMS Rwanda" },
      { num: 8, name: "AGHOUKENG JIOFACK Jean Gérard", rank: "Chargé de Cours", observation: "Chef Cellule MINPLAMAT" },
      { num: 9, name: "CHENDJOU Gilbert", rank: "Chargé de Cours", observation: "En poste" },
      { num: 10, name: "DJIADEU NGAHA Michel", rank: "Chargé de Cours", observation: "En poste" },
      { num: 11, name: "DOUANLA YONTA Herman", rank: "Chargé de Cours", observation: "En poste" },
      { num: 12, name: "FOMEKONG Christophe", rank: "Chargé de Cours", observation: "En poste" },
      { num: 13, name: "KIANPI Maurice", rank: "Chargé de Cours", observation: "En poste" },
      { num: 14, name: "KIKI Maxime Armand", rank: "Chargé de Cours", observation: "En poste" },
      { num: 15, name: "MBAKOP Guy Merlin", rank: "Chargé de Cours", observation: "En poste" },
      { num: 16, name: "MBANG Joseph", rank: "Chargé de Cours", observation: "En poste" },
      { num: 17, name: "MBEHOU Mohamed", rank: "Chargé de Cours", observation: "En poste" },
      { num: 18, name: "MBELE BIDIMA Martin Ledoux", rank: "Chargé de Cours", observation: "En poste" },
      { num: 19, name: "MENGUE MENGUE David Joe", rank: "Chargé de Cours", observation: "En poste" },
      { num: 20, name: "NGUEFACK Bernard", rank: "Chargé de Cours", observation: "En poste" },
      { num: 21, name: "NIMPA PEFOUNKEU Romain", rank: "Chargé de Cours", observation: "En poste" },
      { num: 22, name: "POLA DOUNDOU Emmanuel", rank: "Chargé de Cours", observation: "En poste" },
      { num: 23, name: "TAKAM SOH Patrice", rank: "Chargé de Cours", observation: "En poste" },
      { num: 24, name: "TCHANGANG Roger Duclos", rank: "Chargé de Cours", observation: "En poste" },
      { num: 25, name: "TCHOUNDJA Edgar Landry", rank: "Chargé de Cours", observation: "En poste" },
      { num: 26, name: "TETSADJIO TCHILEPECK M. E.", rank: "Chargée de Cours", observation: "En poste" },
      { num: 27, name: "TIAYA TSAGUE N. Anne-Marie", rank: "Chargée de Cours", observation: "En poste" },
      { num: 28, name: "MBIAKOP Hilaire George", rank: "Assistant", observation: "En poste" },
    ],
  },
  {
    id: "microbiologie",
    code: "MIB",
    name: "Département de Microbiologie",
    count: 13,
    teachers: [
      { num: 1, name: "ESSIA NGANG Jean Justin", rank: "Professeur", observation: "DRV / IMPM" },
      { num: 2, name: "ETOA François Xavier", rank: "Professeur", observation: "Chef de Département / Recteur Univ. Douala" },
      { num: 3, name: "BOYOMO ONANA", rank: "Maître de Conférences", observation: "En poste" },
      { num: 4, name: "NWAGA Dieudonné M.", rank: "Maître de Conférences", observation: "En poste" },
      { num: 5, name: "NYEGUE Maximilienne Ascension", rank: "Maître de Conférences", observation: "Vice-Doyen / DSSE" },
      { num: 6, name: "RIWOM Sara Honorine", rank: "Maître de Conférences", observation: "En poste" },
      { num: 7, name: "SADO KAMDEM Sylvain Leroy", rank: "Maître de Conférences", observation: "En poste" },
      { num: 8, name: "ASSAM ASSAM Jean Paul", rank: "Chargé de Cours", observation: "En poste" },
      { num: 9, name: "BODA Maurice", rank: "Chargé de Cours", observation: "En poste" },
      { num: 10, name: "BOUGNOM Blaise Pascal", rank: "Chargé de Cours", observation: "En poste" },
      { num: 11, name: "ESSONO OBOUGOU Germain G.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 12, name: "NJIKI BIKOÏ Jacky", rank: "Chargée de Cours", observation: "En poste" },
      { num: 13, name: "TCHIKOUA Roger", rank: "Chargé de Cours", observation: "Chef Service Scolarité & Statistiques" },
    ],
  },
  {
    id: "physique",
    code: "PHY",
    name: "Département de Physique",
    count: 39,
    teachers: [
      { num: 1, name: "BEN-BOLIE Germain Hubert", rank: "Professeur", observation: "En poste" },
      { num: 2, name: "ESSIMBI ZOBO Bernard", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "KOFANE Timoléon Crépin", rank: "Professeur", observation: "En poste" },
      { num: 4, name: "NDJAKA Jean Marie Bienvenu", rank: "Professeur", observation: "Chef de Département" },
      { num: 5, name: "NJANDJOCK NOUCK Philippe", rank: "Professeur", observation: "Sous-Directeur / MINRESI" },
      { num: 6, name: "NJOMO Donatien", rank: "Professeur", observation: "En poste" },
      { num: 7, name: "PEMHA Elkana", rank: "Professeur", observation: "En poste" },
      { num: 8, name: "TABOD Charles TABOD", rank: "Professeur", observation: "Doyen Univ. Bamenda" },
      { num: 9, name: "TCHAWOUA Clément", rank: "Professeur", observation: "En poste" },
      { num: 10, name: "WOAFO Paul", rank: "Professeur", observation: "En poste" },
      { num: 11, name: "BIYA MOTTO Frédéric", rank: "Maître de Conférences", observation: "DG / HYDRO Mekin" },
      { num: 12, name: "BODO Bertrand", rank: "Maître de Conférences", observation: "Chef Dpt Énergies Renouvelables" },
      { num: 13, name: "DJUIDJE KENMOE épouse ALOYEM", rank: "Maître de Conférences", observation: "En poste" },
      { num: 14, name: "EKOBENA FOUDA Henri Paul", rank: "Maître de Conférences", observation: "Chef Division UN" },
      { num: 15, name: "EYEBE FOUDA Jean sire", rank: "Maître de Conférences", observation: "En poste" },
      { num: 16, name: "FEWO Serge Ibraïd", rank: "Maître de Conférences", observation: "En poste" },
      { num: 17, name: "HONA Jacques", rank: "Maître de Conférences", observation: "En poste" },
      { num: 18, name: "MBANE BIOUELE César", rank: "Maître de Conférences", observation: "En poste" },
      { num: 19, name: "NANA ENGO Serge Guy", rank: "Maître de Conférences", observation: "Director Students Affairs UB" },
      { num: 20, name: "NANA NBENDJO Blaise", rank: "Maître de Conférences", observation: "En poste" },
      { num: 21, name: "NOUAYOU Robert", rank: "Maître de Conférences", observation: "En poste" },
      { num: 22, name: "SAIDOU", rank: "Maître de Conférences", observation: "Sous-Directeur / MINRESI" },
      { num: 23, name: "SIEWE SIEWE Martin", rank: "Maître de Conférences", observation: "En poste" },
      { num: 24, name: "SIMO Elie", rank: "Maître de Conférences", observation: "En poste" },
      { num: 25, name: "VONDOU Derbetini Appolinaire", rank: "Maître de Conférences", observation: "En poste" },
      { num: 26, name: "WAKATA née BEYA Annie", rank: "Maître de Conférences", observation: "Sous-Directeur / MINESUP" },
      { num: 27, name: "ZEKENG Serge Sylvain", rank: "Maître de Conférences", observation: "En poste" },
      { num: 28, name: "ABDOURAHIMI", rank: "Chargé de Cours", observation: "En poste" },
      { num: 29, name: "EDONGUE HERVAIS", rank: "Chargé de Cours", observation: "En poste" },
      { num: 30, name: "ENYEGUE A NYAM épse BELINGA", rank: "Chargée de Cours", observation: "En poste" },
      { num: 31, name: "FOUEDJIO David", rank: "Chargé de Cours", observation: "Chef Cell. MINADER" },
      { num: 32, name: "MBINACK Clément", rank: "Chargé de Cours", observation: "En poste" },
      { num: 33, name: "MBONO SAMBA Yves Christian U.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 34, name: "MELI’I Joelle Larissa", rank: "Chargée de Cours", observation: "En poste" },
      { num: 35, name: "MVOGO Alain", rank: "Chargé de Cours", observation: "En poste" },
      { num: 36, name: "NDOP Joseph", rank: "Chargé de Cours", observation: "En poste" },
      { num: 37, name: "OBOUNOU Marcel", rank: "Chargé de Cours", observation: "DA / Univ Inter-État Sangmélima" },
      { num: 38, name: "WOULACHE Rosalie Laure", rank: "Chargée de Cours", observation: "En poste" },
      { num: 39, name: "CHAMANI Roméo", rank: "Assistant", observation: "En poste" },
    ],
  },
  {
    id: "sciences-de-la-terre",
    code: "ST",
    name: "Département des Sciences de la Terre et de l'Univers",
    count: 43,
    teachers: [
      { num: 1, name: "BITOM Dieudonné", rank: "Professeur", observation: "Doyen / FASA / UDs" },
      { num: 2, name: "FOUATEU Rose épse YONGUE", rank: "Professeur", observation: "En poste" },
      { num: 3, name: "KAMGANG Pierre", rank: "Professeur", observation: "En poste" },
      { num: 4, name: "MEDJO EKO Robert", rank: "Professeur", observation: "Conseiller Technique / UYII" },
      { num: 5, name: "NDJIGUI Paul Désiré", rank: "Professeur", observation: "Chef de Département / Vice-Doyen" },
      { num: 6, name: "NKOUMBOU Charles", rank: "Professeur", observation: "En poste" },
      { num: 7, name: "NZENTI Jean-Paul", rank: "Professeur", observation: "En poste" },
      { num: 8, name: "ABOSSOLO née ANGUE Monique", rank: "Maître de Conférences", observation: "Vice-Doyen / DRC" },
      { num: 9, name: "GHOGOMU Richard TANWI", rank: "Maître de Conférences", observation: "CD / UMa" },
      { num: 10, name: "MOUNDI Amidou", rank: "Maître de Conférences", observation: "CT / MINIMDT" },
      { num: 11, name: "NDAM NGOUPAYOU Jules-Remy", rank: "Maître de Conférences", observation: "En poste" },
      { num: 12, name: "NGOS III Simon", rank: "Maître de Conférences", observation: "DAAC / UMa" },
      { num: 13, name: "NJILAH Isaac KONFOR", rank: "Maître de Conférences", observation: "En poste" },
      { num: 14, name: "ONANA Vincent Laurent", rank: "Maître de Conférences", observation: "En poste" },
      { num: 15, name: "BISSO Dieudonné", rank: "Maître de Conférences", observation: "Directeur Projet Barrage Memve'ele" },
      { num: 16, name: "EKOMANE Emile", rank: "Maître de Conférences", observation: "En poste" },
      { num: 17, name: "GANNO Sylvestre", rank: "Maître de Conférences", observation: "En poste" },
      { num: 18, name: "NYECK Bruno", rank: "Maître de Conférences", observation: "En poste" },
      { num: 19, name: "TCHOUANKOUE Jean-Pierre", rank: "Maître de Conférences", observation: "En poste" },
      { num: 20, name: "TEMDJIM Robert", rank: "Maître de Conférences", observation: "En poste" },
      { num: 21, name: "YENE ATANGANA Joseph Q.", rank: "Maître de Conférences", observation: "Chef Div. / MINTP" },
      { num: 22, name: "ZO’O ZAME Philémon", rank: "Maître de Conférences", observation: "DG / ART" },
      { num: 23, name: "ANABA ONANA Achille Basile", rank: "Chargé de Cours", observation: "En poste" },
      { num: 24, name: "BEKOA Etienne", rank: "Chargé de Cours", observation: "En poste" },
      { num: 25, name: "ELISE SABABA", rank: "Chargé de Cours", observation: "En poste" },
      { num: 26, name: "ESSONO Jean", rank: "Chargé de Cours", observation: "En poste" },
      { num: 27, name: "EYONG JOHN TAKEM", rank: "Chargé de Cours", observation: "En poste" },
      { num: 28, name: "FUH Calistus Gentry", rank: "Chargé de Cours", observation: "Secrétaire d’État / MINMIDT" },
      { num: 29, name: "LAMILEN BILLA Daniel", rank: "Chargé de Cours", observation: "En poste" },
      { num: 30, name: "MBESSE Cécile Olive", rank: "Chargée de Cours", observation: "En poste" },
      { num: 31, name: "MBIDA YEM", rank: "Chargé de Cours", observation: "En poste" },
      { num: 32, name: "METANG Victor", rank: "Chargé de Cours", observation: "En poste" },
      { num: 33, name: "MINYEM Dieudonné-Lucien", rank: "Chargé de Cours", observation: "CD / UMa" },
      { num: 34, name: "MOUAFO Lucas", rank: "Chargé de Cours", observation: "En poste" },
      { num: 35, name: "NGO BELNOUN Rose Noël", rank: "Chargée de Cours", observation: "En poste" },
      { num: 36, name: "NTSAMA ATANGANA Jacqueline", rank: "Chargée de Cours", observation: "En poste" },
      { num: 37, name: "NGO BIDJECK Louise Marie", rank: "Chargée de Cours", observation: "En poste" },
      { num: 38, name: "NGUEUTCHOUA Gabriel", rank: "Chargé de Cours", observation: "CEA / MINRESI" },
      { num: 39, name: "NOMO NEGUE Emmanuel", rank: "Chargé de Cours", observation: "En poste" },
      { num: 40, name: "TCHAKOUNTE J. épse NOUMBEM", rank: "Chargée de Cours", observation: "Chef Cell. / MINRESI" },
      { num: 41, name: "TCHAPTCHET TCHATO De P.", rank: "Chargé de Cours", observation: "En poste" },
      { num: 42, name: "TEHNA Nathanaël", rank: "Chargé de Cours", observation: "En poste" },
      { num: 43, name: "TEMGA Jean Pierre", rank: "Chargé de Cours", observation: "En poste" },
    ],
  },
];
